### ISSUE TITLE
"unknown error (http status: 413)" when uploading sourcemaps

### ISSUE THREAD

**Issue by tommynordli** [getsentry/sentry-react-native#1260]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 2.1.0

**`react-native` version:** 0.63.4

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [ ]  sentry.io (SaaS)
- [x]  on-premise

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: 'https://...@sentry.company.com/...'
});
```

---
**I have following issue:**

After moving our Sentry installation over to self-hosted I haven't been able to upload bundle and sourcemaps. I have completely reinstalled `@sentry/react-native`, gone through the installation steps, run `sentry-wizard`, and made sure my `sentry.properties` looks correct. Also made sure we have no `client_max_body_size` on our server. It's happening on both iOS and Android. 

**Steps to reproduce:**
- Host sentry on-premise
- Follow sentry installation steps
- Build for release

**Actual result:**

```
> Bundled 2 files for upload
error: API request failed
  caused by: sentry reported an error: unknown error (http status: 413)
API request failed

  DEBUG   2020-12-23 11:13:13.573074 +01:00 client close; no transport to shut down  (from sentry)
  DEBUG   2020-12-23 11:13:13.573089 +01:00 skipping update nagger because session is not attended

> Task :app:bundleReleaseJsAndAssets_SentryUpload_310 FAILED
  caused by: sentry reported an error: unknown error (http status: 413)

Execution failed for task ':app:bundleReleaseJsAndAssets_SentryUpload_310'.
> Process 'command '/Users/tommy/Git/noisolation/FamilyFrame/node_modules/@sentry/cli/bin/sentry-cli'' finished with non-zero exit value 1
```

**Expected result:**

Successfully build and uploading bundle and sourcemaps to Sentry

**Comment by walterholohan** [comment]
I am getting the same error when uploading sourcemaps. However, I am not on a self-hosted version.

**Comment by walterholohan** [comment]
I fixed the issue by creating a new auth token. The previous auth token was invalid as the guy in our team who initially created the token left the organisation just before Christmas. So his token was invalidated.

**Comment by jennmueng** [comment]
Hmm a 413 error means that the file is too large, how large are your source maps? Otherwise you may not have `client_max_body_size` currently set, but maybe try setting it to a higher value in your `nginx.conf`.

**Comment by walterholohan** [comment]
Sorry ignore my comments. I was getting a 403 error

**Comment by tommynordli** [comment]
> Hmm a 413 error means that the file is too large, how large are your source maps? Otherwise you may not have `client_max_body_size` currently set, but maybe try setting it to a higher value in your `nginx.conf`.

I have also tried setting `client_max_body_size` to 500m, but still getting the same error. The source maps are 3.6mb

**Comment by marandaneto** [comment]
@chadwhitacre does it make sense to move it to @getsentry/sentry ? looks like a server-side issue rather than SDK.

**Comment by chadwhitacre** [comment]
Sure thing, go for it @marandaneto. 👍

**Comment by chadwhitacre** [comment]
Actually, let's move to `onpremise` since it seems to be self-hosting specific.
