### ISSUE TITLE
[iOS] OutOfMemory errors dont seem reliable on 2.5.2

### ISSUE THREAD

**Issue by RenatoSerra22** [getsentry/sentry-react-native#1633]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io) 

Which SDK and version?
Sentry: 2.5.2
React native: 0.63.4
React: 16.13.1

### Steps to Reproduce

I've upgraded to 2.5.2 and on iOS i keep seeing OutOfMemory exceptions on sentry, even from simulator sessions that i ran and know the app didn't crash and memory looked good. Also no crashes reported on appstore connect on firebase.

**Comment by jennmueng** [comment]
Routing this to @philipphofmann, for reference here's this occurring from our sample app on a simulator that didn't crash: https://sentry.io/organizations/sentry-sdks/issues/2355695161/

**Comment by RenatoSerra22** [comment]
Probably related to the cocoa bug https://github.com/getsentry/sentry-cocoa/issues/1185 , my heart almost exploded when i saw most of my users were "crashing" on a new release 😢

**Comment by philipphofmann** [comment]
I'm deeply sorry about that, @RenatoSerra22. We are going to fix this. To stop your heart from exploding, maybe it's best to disable out-of-memory tracking for now.

**Comment by ku8ar** [comment]
@philipphofmann how to do that?
In our app, right now OutOfMemory error counts codepush upgrades on Sentry :D

**Comment by RenatoSerra22** [comment]
i think `enableOutOfMemoryTracking` is not available on the initializer in react react native

**Comment by jennmueng** [comment]
@RenatoSerra22 You can pass `enableOutOfMemoryTracking: false` to `Sentry.init` and it'll go through to iOS. Typescript will complain but it will go through nonetheless.

**Comment by philipphofmann** [comment]
> @philipphofmann how to do that?
> In our app, OutOfMemory error counts codepush upgrades on Sentry :D

You find the answer here: https://docs.sentry.io/platforms/apple/configuration/out-of-memory/ @ku8ar

**Comment by aryo** [comment]
After disabling OOMTracking, we went from thousands of errors to under ten, but we're still getting them nonetheless.

Not sure of the reporting mechanism, but is it possible for the following sequence of events to happen?
1. OOM error captured 
2. User upgrades to version with OOMTracking disabled
3. On app start, error gets shipped
4. The error on the Sentry dashboard says the user was on the latest version of the app

We are disabling it on the native side in AppDelegate's `didFinishLaunchingWithOptions`.

**Comment by raimonkh** [comment]
We also seeing a lot of this errors. Is this still an issue and you recommend disabling OOMTracking? Or we just update new Sentry 2.6?

**Comment by jaexplorer** [comment]
I'm suddenly seeing alot of these on IOS. Any update to fix?

**Comment by raimonkh** [comment]
@jaexplorer as https://github.com/getsentry/sentry-react-native/issues/1633#issuecomment-869156850 says, disable it, I think it can be toggled for X amount of days.
I haven't found the solution, I believe this happens since version 2.5... on RN lib

**Comment by bruno-garcia** [comment]
Resolved in the cocoa SDK: https://github.com/getsentry/sentry-cocoa/issues/1252

**Comment by bruno-garcia** [comment]
SDK version 3.0.3 should already include this fix

**Comment by stewartmcgown** [comment]
@Asvarox We're currently seeing a lot of these OutOfMemory crashes - not sure if they are real crashes or not. Did you find out the problem?

**Comment by savv** [comment]
[sorry for the double posting [here](https://github.com/getsentry/sentry-cocoa/issues/1185#issuecomment-940825075) - this seems like a more relevant place]

Sadly, I'm still getting this error. We are using Sentry via its React Native integration, which is on 7.3.0. It does not seem to be a legitimate OOM, and we are only getting it in our staging version where we recently upgraded sentry to the latest version (2.4.2 => 3.1.1).

The Podfile.lock shows that Sentry/Core (= 7.3.0) is installed. It previously showed: Sentry/Core (= 6.1.4).

**Comment by icecapp** [comment]
just installed sentry last week and noticed in the logs we've been getting this error since. there is no actual memory issue in the app itself.
