### ISSUE TITLE
High Failure Rate while using new SDK automatic instrumentation

### ISSUE THREAD

**Issue by adityaputra11** [getsentry/sentry-react-native#2426]
**OS:**
- [ ]  Windows
- [X]  MacOS
- [ ]  Linux

**Platform:**
- [ ]  iOS
- [X]  Android

**SDK:**
- [X]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 4.1.2

**`react-native` version:** 0.67.4

**Are you using Expo?**
- [ ]  Yes
- [X]  No

**Are you using sentry.io or on-premise?**
- [X]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[[Link to issue]](https://sentry.io/organizations/flipid/performance/?isDefaultQuery=false&metricSearchSetting=transactionsOnly&query=release%3Aid.flip%402.8.0%2B257)

**Configuration:**

(`@sentry/react-native`)
```
 Sentry.init({
        onReady: () => {
            console.log(
                `initialize sentry tracesampleRate: ${tracesSampleRate} sampleRate:${sampleRate}`,
            );
        },
        dsn:DSN,
        debug:false,
        release:`${appVersion}`,
        dist:`${versionCode}`,
        environment:'android-production',
        sampleRate,
        tracesSampleRate,
        maxBreadcrumbs,
        integrations,
        enableOutOfMemoryTracking:false,
        attachStacktrace: true,
        beforeSend,
        beforeBreadcrumb
    });
```

---
**I have following issue:**
in dashboard sentry i found a very high failure rate, this happened when i upgraded the sdk to a newer version, also i have tried update to 4.2.3 but still face the same issue

[Description]

**Steps to reproduce:**
- Step 1 install @sentry/react-native v 4.1.2
- Step 2 build and run app

**Actual result:**
failure rate is so hight while using automatic instrumentation

[Actual result]

**Expected result:**

no failure rate
[Expected result]

**Comment by marandaneto** [comment]
https://docs.sentry.io/product/performance/metrics/#failure-rate
The problem is that your transactions are being finished with the status of `deadline_exceeded`.

Are you using the `ReactNativeTracing` integration?
Are you using the default values of `idleTimeout` and `maxTransactionDuration` or custom values?

**Comment by adityaputra11** [comment]
yes i am using default idleTimeout and maxTransactionDuration
but when i change idleTimeout to 3000 still facing the same problem

**Comment by marandaneto** [comment]
https://github.com/getsentry/sentry-react-native/pull/2427 should fix it.

**Comment by adityaputra11** [comment]
sure will trying to patch

**Comment by adityaputra11** [comment]
thanks you very much

**Comment by adityaputra11** [comment]
![Screen Shot 2022-08-18 at 15 45 50](https://user-images.githubusercontent.com/24503826/185352714-9549da49-0ae1-4a06-b5f7-f021d06c297b.png)

still facing issue after patch
also i have set idleTimeout and maxTransactionDuration to 5000 but still got deadline_exceeded

**Comment by marandaneto** [comment]
@adityaputra11 keep both default values, `maxTransactionDuration` should be always much longer than `idleTimeout`.
How are you testing it? the SDK isn't released yet.

**Comment by adityaputra11** [comment]
whoa i see, i am write manual on node_module base on this MR https://github.com/getsentry/sentry-react-native/pull/2427

**Comment by adityaputra11** [comment]
![Screen Shot 2022-08-18 at 17 16 17](https://user-images.githubusercontent.com/24503826/185371793-07391963-7277-49fe-8a26-d09efab9a94f.png)
already fixed with set ``maxTransactionDuration`` longer than ``idleTimeout``
will waiting for SDK release
