### ISSUE TITLE
Migrating from 4.15.0 to 5.0.0: Command PhaseScriptExecution failed with a nonzero exit code

### ISSUE THREAD

**Issue by sweatherall** [getsentry/sentry-react-native#2862]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [ ]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 5.0.0

**`react-native` version:** 0.71.3

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: https://0e607a3e9cc8417a832a7a77952479c7@o171571.ingest.sentry.io/1250057,
  environment: dev,
});
```

---
**I have following issue:**

During iOS build in XCode, I'm getting this build error:
```
FBReactNativeSpec
error build: Command PhaseScriptExecution failed with a nonzero exit code
```

**Steps to reproduce:**
- Followed the [migration guide](https://docs.sentry.io/platforms/react-native/migration/#from-4x-to-5x) from 4.x to 5.x (we were previously on 4.15.0)
- I tried applying this fix: https://docs.sentry.io/platforms/react-native/troubleshooting/#ios-build-script-failed
- I also tried this fix: https://docs.sentry.io/platforms/react-native/troubleshooting/#using-node-with-nvm-or-volta
- Neither of the above fixes worked, and I am not sure what to try next.

**Actual result:**

Build error described above:
```
FBReactNativeSpec
error build: Command PhaseScriptExecution failed with a nonzero exit code
```

**Expected result:**

Successful iOS build

**Comment by krystofwoldrich** [comment]
Hi, can you share your `Bundle React Native code and images` build phase?

You can add `--log-level=debug --force-foreground` to the CLI to see more logs.
```bash
/bin/sh -c "$WITH_ENVIRONMENT \"../../node_modules/@sentry/cli/bin/sentry-cli react-native xcode $REACT_NATIVE_XCODE --log-level=debug --force-foreground\""
```

**Comment by krystofwoldrich** [comment]
Closing this due to inactivity. If this is still an issue feel free to comment here or open a new issue if the context changed.

**Comment by sweatherall** [comment]
Sorry for the delay.

Here is the `Bundle React Native code and images` build phase:
```
export SENTRY_PROPERTIES=sentry.properties
export EXTRA_PACKAGER_ARGS="--sourcemap-output $DERIVED_FILE_DIR/main.jsbundle.map"
set -e
export SENTRY_PROPERTIES=sentry.properties
export EXTRA_PACKAGER_ARGS="--sourcemap-output $DERIVED_FILE_DIR/main.jsbundle.map"
WITH_ENVIRONMENT="../node_modules/react-native/scripts/xcode/with-environment.sh"
REACT_NATIVE_XCODE="../node_modules/react-native/scripts/react-native-xcode.sh"
SENTRY_CLI_PATH="../node_modules/@sentry/cli/bin/sentry-cli"
/bin/sh -c "$WITH_ENVIRONMENT \"$SENTRY_CLI_PATH react-native xcode \"../node_modules/@sentry/cli/bin/sentry-cli react-native xcode $REACT_NATIVE_XCODE --log-level=debug --force-foreground\"\""
/bin/sh ../node_modules/@sentry/react-native/scripts/collect-modules.sh

```

**Comment by sweatherall** [comment]
@krystofwoldrich let me know if you need any more info - I tried again the other day (this time with the latest `v5.1.1`) and am still getting the same error.

**Comment by krystofwoldrich** [comment]
@sweatherall Hi, thank you for the reply.

Here is the fixed script.
```bash
set -e

export SENTRY_PROPERTIES=sentry.properties
export EXTRA_PACKAGER_ARGS="--sourcemap-output $DERIVED_FILE_DIR/main.jsbundle.map"

WITH_ENVIRONMENT="../node_modules/react-native/scripts/xcode/with-environment.sh"
REACT_NATIVE_XCODE="../node_modules/react-native/scripts/react-native-xcode.sh"
SENTRY_CLI_PATH="../node_modules/@sentry/cli/bin/sentry-cli"

/bin/sh -c "$WITH_ENVIRONMENT \"$SENTRY_CLI_PATH react-native xcode $REACT_NATIVE_XCODE --log-level=debug --force-foreground\""

/bin/sh ../node_modules/@sentry/react-native/scripts/collect-modules.sh
```

Could you describe the steps you did during the upgrade from 4.x to 5.x, I would like try figure what cause the corrupted build script.

**Comment by sweatherall** [comment]
I followed the [Getting Started](https://docs.sentry.io/platforms/react-native/) guide.
So I essentially npm installed the newest version, and then ran the suggested script: `npx @sentry/wizard -i reactNative -p ios android`
Followed by running `pod install`

I updated the script with your suggested codeblock above - but I am unfortunately getting the same error.

I have also tried cleaning the build folder and building again, but same error :( 

If I can provide any other information please let me know. I hope we can uncover what I have done incorrectly..!
Or if you have another suggested method of upgrading from 4.x -> 5.x please let me know.

**Comment by sweatherall** [comment]
@krystofwoldrich sorry to tag you, I'm just wondering if there is anything else I can try here

**Comment by jaexplorer** [comment]
Yeah I can't seem to get v5 working, v4 is fine.
On IOS builds fine locally, but on bitrise fails with very little helpful information.

**Comment by krystofwoldrich** [comment]
@sweatherall Thank you for tagging me and bringing this to our attention. 

If I understand correctly you are using [this](https://github.com/getsentry/sentry-react-native/issues/2862#issuecomment-1479626665) script but still getting the same error.

Could you share your script and build logs output?

@jaexplorer Hi, sorry to hear that the v5 is not working for you. Could you check the build script if there is no mistake in it, and compare it with [this](https://github.com/getsentry/sentry-react-native/issues/2862#issuecomment-1479626665)? Or share it here with the failed build logs.

Note [the use of](https://github.com/getsentry/sentry-react-native/issues/2862#issuecomment-1479626665) `--log-level=debug --force-foreground` using this we can get more detailed logs to debug the issue.

**Comment by jaexplorer** [comment]
Hey @krystofwoldrich thanks for the message, yes I did try the script you posted. 
Do you know where or roughly what the logs would look like? I'm struggling to see them, I'll post them when I find them.

**Comment by jaexplorer** [comment]
This is what I get @krystofwoldrich

Please note I only get this when I upgrade Sentry from 4.8.0 to the latest (5.3.0), no other changes are done. This only occurs on Bitrise, locally it builds fine. If the below logs make sense to you, please steer me in the right direction.

The following build commands failed:
	PhaseScriptExecution [CP-User]\ Generate\ Specs /Users/[REDACTED]/Library/Developer/Xcode/DerivedData/[REDACTED]-epebssieaqihhlfgbtqcvcnrlvyj/Build/Intermediates.noindex/ArchiveIntermediates/[REDACTED]-UAT/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/FBReactNativeSpec.build/Script-46EB2E0002F1E0.sh (in target 'FBReactNativeSpec' from project 'Pods')
(1 failure)
You can find the last couple of lines of Xcode's build log above, but the full log will be also available in the xcodebuild-archive.log

Failed to execute Step main logic:
  failed to archive the project:
    command failed with exit status 65 (set -o pipefail && xcodebuild "archive" "-workspace" "/Users/[REDACTED]/git/ios/[REDACTED].xcworkspace" "-scheme" "[REDACTED]-UAT" "-configuration" "Release" "-xcconfig" "/var/folders/xq/sfn_fz953jb36ptp2g68wc2r0000gn/T/3044486319/temp.xcconfig" "-archivePath" "/var/folders/xq/sfn_fz953jb36ptp2g68wc2r0000gn/T/xcodeArchive1214225304/[REDACTED]-UAT.xcarchive" "-destination" "generic/platform=iOS" "-UseModernBuildSystem=YES" | xcpretty)

**Comment by krystofwoldrich** [comment]
@jaexplorer Good starting point is to search for

```
                Welcome to Metro v0.73.8
              Fast - Scalable - Integrated
```

After the bundle is created sentry tries to upload it.

```
Processing react-native sourcemaps for Sentry upload.
```

If none of these is present try to search for the beginning of the `Bundle` build phase.

```
PhaseScriptExecution Bundle\ React\ Native\ code\ and\ images
```

And go from there.

Can you share your `Bundle React Native code and images` after the upgrade to v5?

**Comment by jaexplorer** [comment]
@krystofwoldrich looks like it never gets to any of those, must be failing beforehand. But since Sentry is the only change I wonder what it could be?

**Comment by krystofwoldrich** [comment]
@jaexplorer And if you follow the log from the beginning of the `Bundle React Native code and images` there are no errors?

**Comment by jaexplorer** [comment]
@krystofwoldrich I'm saying it looks like it's not getting to Bundle React Native code and images phase. It doesn't appear in the logs at all

**Comment by krystofwoldrich** [comment]
@jaexplorer Thank you for the clarification,
I misunderstood that it errors out before the commands in the `Bundle` build phase.

That's strange, I don't know what to advise if there is no more information about the failed build. 

Maybe try step by step, run the build with the SDK v5 but with the original build phases, then add them back.

**Comment by sweatherall** [comment]
My experience sounds similar to @jaexplorer - there are no logs to help / it errors out before the commands in the Bundle build phase.
All I have to go off of is this: 
<img width="274" alt="Screen Shot 2023-04-21 at 5 05 33 PM" src="https://user-images.githubusercontent.com/4127588/233734600-fad705f5-2490-4a88-b166-698a5b8d6b70.png">

Which links to the `[CP-User] Generate Specs` build phase.
That build phase looks like this: 
```
pushd "$PODS_ROOT/../" > /dev/null
RCT_SCRIPT_POD_INSTALLATION_ROOT=$(pwd)
popd >/dev/null

export RCT_SCRIPT_RN_DIR=${PODS_TARGET_SRCROOT}/../..
export RCT_SCRIPT_LIBRARY_NAME=FBReactNativeSpec
export RCT_SCRIPT_OUTPUT_DIR=$RCT_SCRIPT_POD_INSTALLATION_ROOT/build/generated/ios
export RCT_SCRIPT_LIBRARY_TYPE=modules
export RCT_SCRIPT_JS_SRCS_PATTERN=Native*.js
export RCT_SCRIPT_JS_SRCS_DIR=../../Libraries
export RCT_SCRIPT_CODEGEN_MODULE_DIR=.
export RCT_SCRIPT_CODEGEN_COMPONENT_DIR=react/renderer/components
export RCT_SCRIPT_FILE_LIST="[\"../../Libraries/ActionSheetIOS/NativeActionSheetManager.js\", \"../../Libraries/Alert/NativeAlertManager.js\", \"../../Libraries/Animated/NativeAnimatedHelper.js\", \"../../Libraries/Animated/NativeAnimatedModule.js\", \"../../Libraries/Animated/NativeAnimatedTurboModule.js\", \"../../Libraries/AppState/NativeAppState.js\", \"../../Libraries/BatchedBridge/NativeModules.js\", \"../../Libraries/Blob/NativeBlobModule.js\", \"../../Libraries/Blob/NativeFileReaderModule.js\", \"../../Libraries/BugReporting/NativeBugReporting.js\", \"../../Libraries/Components/AccessibilityInfo/NativeAccessibilityInfo.js\", \"../../Libraries/Components/AccessibilityInfo/NativeAccessibilityManager.js\", \"../../Libraries/Components/Clipboard/NativeClipboard.js\", \"../../Libraries/Components/DatePickerAndroid/NativeDatePickerAndroid.js\", \"../../Libraries/Components/Keyboard/NativeKeyboardObserver.js\", \"../../Libraries/Components/Sound/NativeSoundManager.js\", \"../../Libraries/Components/StatusBar/NativeStatusBarManagerAndroid.js\", \"../../Libraries/Components/StatusBar/NativeStatusBarManagerIOS.js\", \"../../Libraries/Components/ToastAndroid/NativeToastAndroid.js\", \"../../Libraries/Core/NativeExceptionsManager.js\", \"../../Libraries/Core/SegmentFetcher/NativeSegmentFetcher.js\", \"../../Libraries/Core/Timers/NativeTiming.js\", \"../../Libraries/EventEmitter/NativeEventEmitter.js\", \"../../Libraries/EventEmitter/__mocks__/NativeEventEmitter.js\", \"../../Libraries/HeapCapture/NativeJSCHeapCapture.js\", \"../../Libraries/Image/NativeImageEditor.js\", \"../../Libraries/Image/NativeImageLoaderAndroid.js\", \"../../Libraries/Image/NativeImageLoaderIOS.js\", \"../../Libraries/Image/NativeImageStoreAndroid.js\", \"../../Libraries/Image/NativeImageStoreIOS.js\", \"../../Libraries/Interaction/NativeFrameRateLogger.js\", \"../../Libraries/Linking/NativeIntentAndroid.js\", \"../../Libraries/Linking/NativeLinkingManager.js\", \"../../Libraries/Modal/NativeModalManager.js\", \"../../Libraries/NativeComponent/NativeComponentRegistry.js\", \"../../Libraries/NativeComponent/NativeComponentRegistryUnstable.js\", \"../../Libraries/NativeModules/specs/NativeAnimationsDebugModule.js\", \"../../Libraries/NativeModules/specs/NativeDevMenu.js\", \"../../Libraries/NativeModules/specs/NativeDevSettings.js\", \"../../Libraries/NativeModules/specs/NativeDeviceEventManager.js\", \"../../Libraries/NativeModules/specs/NativeDialogManagerAndroid.js\", \"../../Libraries/NativeModules/specs/NativeLogBox.js\", \"../../Libraries/NativeModules/specs/NativeRedBox.js\", \"../../Libraries/NativeModules/specs/NativeSourceCode.js\", \"../../Libraries/Network/NativeNetworkingAndroid.js\", \"../../Libraries/Network/NativeNetworkingIOS.js\", \"../../Libraries/Performance/NativeJSCSamplingProfiler.js\", \"../../Libraries/PermissionsAndroid/NativePermissionsAndroid.js\", \"../../Libraries/PushNotificationIOS/NativePushNotificationManagerIOS.js\", \"../../Libraries/ReactNative/NativeHeadlessJsTaskSupport.js\", \"../../Libraries/ReactNative/NativeI18nManager.js\", \"../../Libraries/ReactNative/NativeUIManager.js\", \"../../Libraries/Settings/NativeSettingsManager.js\", \"../../Libraries/Share/NativeShareModule.js\", \"../../Libraries/TurboModule/samples/NativeSampleTurboModule.js\", \"../../Libraries/Utilities/NativeAppearance.js\", \"../../Libraries/Utilities/NativeDevLoadingView.js\", \"../../Libraries/Utilities/NativeDevSplitBundleLoader.js\", \"../../Libraries/Utilities/NativeDeviceInfo.js\", \"../../Libraries/Utilities/NativePlatformConstantsAndroid.js\", \"../../Libraries/Utilities/NativePlatformConstantsIOS.js\", \"../../Libraries/Vibration/NativeVibration.js\", \"../../Libraries/WebPerformance/NativePerformanceObserver.js\", \"../../Libraries/WebSocket/NativeWebSocketModule.js\"]"

SCRIPT_PHASES_SCRIPT="$RCT_SCRIPT_RN_DIR/scripts/react_native_pods_utils/script_phases.sh"
WITH_ENVIRONMENT="$RCT_SCRIPT_RN_DIR/scripts/xcode/with-environment.sh"
/bin/sh -c "$WITH_ENVIRONMENT $SCRIPT_PHASES_SCRIPT"
```

**Comment by krystofwoldrich** [comment]
@sweatherall Hi, can you try `rm -rf Podfile.lock Pods` and then reinstall pods.

Would you be able to send a minimal reproducible example it would be a tremendous help with debugging this issue?

**Comment by jaexplorer** [comment]
@krystofwoldrich just FYI as I mentioned above, I can run and archive my app perfectly fine on local. Its when we use a CI tool like bitrise, builds fail. With the sentry upgrade from v4 to v5 being the only change. Has there been breaking changes surrounding CI?

**Comment by mohit23x** [comment]
yes, the same problem build works locally but fails in CI. 
Here's the log

```
Node found at: /Users/distiller/.nvm/versions/node/v18.16.0/bin/node
node:internal/child_process:413
    throw errnoException(err, 'spawn');
    ^

Error: spawn Unknown system error -8
    at ChildProcess.spawn (node:internal/child_process:413:11)
    at Object.spawn (node:child_process:757:9)
    at Object.<anonymous> (/Users/distiller/project/node_modules/@sentry/cli/bin/sentry-cli:9:4)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47 {
  errno: -8,
  code: 'Unknown system error -8',
  syscall: 'spawn'
}

Node.js v18.16.0
Command PhaseScriptExecution failed with a nonzero exit code
```

**Comment by krystofwoldrich** [comment]
@jaexplorer @mohit23x How do you install node dependencies? `sentry-cli` depends on a post-install script to download its' binary. The missing `sentry-cli` binary could be the cause of the build phase failing.

You can try to install the dep explicitly:

```bash
yarn add @sentry/cli
npm install @sentry/cli
```

**Comment by import-yuv** [comment]
@krystofwoldrich Could you please share the working upload debug symbol script , We're on React Native version `0.71.11`, @sentry/react-native is on `5.4.2` and node-version: "18.16.0, in CI we're getting this error  

Error: 
** ARCHIVE FAILED **


The following build commands failed:
	PhaseScriptExecution Upload\ Debug\ Symbols\ to\ Sentry

**Comment by krystofwoldrich** [comment]
@import-yuv The code example is here https://docs.sentry.io/platforms/react-native/manual-setup/manual-setup/#upload-debug-symbols-to-sentry

If case it doesn't work please open a new issue with the whole log to see what the error is.
