### ISSUE TITLE
SentryBinaryImageCache.h File not Found On RN 0.71.4

### ISSUE THREAD

**Issue by dasfisch** [getsentry/sentry-react-native#3241]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [ ]  Android

**SDK:**
- [ ]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)
- [x] `@sentry/wizard@latest`

**SDK version:** 5.9.0

**`react-native` version:** 0.71.4

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[Link to issue] N/A

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({ 
  dsn: 'https://_____@_____.ingest.sentry.io/_____', 
});
```

---
**I have following issue:**
After running `npx @sentry/wizard@latest -s -i reactNative`, I see that everything successfully completes. However, when I run `npm run ios`, I get the following errors:

```
❌  /Users/sebastianfrohm/repos/native_app/node_modules/@sentry/react-native/ios/RNSentry.mm:14:9: 'Sentry/SentryBinaryImageCache.h' file not found

#import <Sentry/SentryBinaryImageCache.h>
```

Seems like there is a missing file which I am unsure how to link. I am happy to provide more information/configs/et al. Any information or advice would be great. Android works fine! Thank you!

**Steps to reproduce:**
- Run `npx @sentry/wizard@latest -s -i reactNative`
- Complete process
- Run `npm run ios`
- Notice failures.

**Actual result:**

```
❌  /Users/sebastianfrohm/repos/native_app/node_modules/@sentry/react-native/ios/RNSentry.mm:14:9: 'Sentry/SentryBinaryImageCache.h' file not found

#import <Sentry/SentryBinaryImageCache.h>
```

**Expected result:**

`npm run ios` does not throw errors.

**Comment by peterlazar1993** [comment]
Confirming that I have the same issue on React Native 0.72.3

**Comment by januswel** [comment]
`sentry/react-native` 5.8.1 works fine, but I got the same issue when I upgraded to 5.9.0

**Comment by TomCorvus** [comment]
Same as https://github.com/getsentry/sentry-react-native/issues/3240

**Comment by Chahatchugh** [comment]
5.8.1 also throws same error .

**Comment by nmeibergen** [comment]
Same issue here on RN 0.71.7

**Comment by TomCorvus** [comment]
It is not related to the version of RN but to the latest Sentry RN version (5.9.0)
@Chahatchugh you need to update Podfiles `(pod install --repo-update` or `pod update Sentry/HybridSDK`) If you have already done this, don't forget to set a tilde on `@sentry/react-native` version range to avoid yarn or npm from downloading the next minor version.
Like this:
`"@sentry/react-native": "~5.8.1"`

**Comment by renatomserra** [comment]
Started having the same issue today in RN 0.69.9 with sentry 5.5.0

**Comment by kahest** [comment]
closed as duplicate of https://github.com/getsentry/sentry-react-native/issues/3240

**Comment by Hel5ing** [comment]
Same issue on RN 0.70.6

**Comment by Biplovkumar** [comment]
'Sentry/SentryBinaryImageCache.h' file not found issue is still coming in Latest versions. Please reopen the issue and solve this. Need permanent solution.

`  "react": "18.2.0",
    "react-native": "0.72.4",
     "@sentry/react-native": "^5.9.0"`

**Comment by Biplovkumar** [comment]
> ersion range to avoid yarn or npm from downloading the next minor versio

this one is the temporary solution. and really it is working fine.  thanks @TomCorvus.  I think sentry will fix the bug in next versions.

**Comment by kahest** [comment]
> 'Sentry/SentryBinaryImageCache.h' file not found issue is still coming in Latest versions. Please reopen the issue and solve this. Need permanent solution.
> 
> ` "react": "18.2.0", "react-native": "0.72.4", "@sentry/react-native": "^5.9.0"`

See https://github.com/getsentry/sentry-react-native/issues/3241#issuecomment-1680438126 - we will have a fix ready soon.

**Comment by kahest** [comment]
This has been fixed in https://github.com/getsentry/sentry-react-native/releases/tag/5.9.1

**Comment by Biplovkumar** [comment]
thanks @kahest  for information.

Now i have updated `5.9.1`. But now it is giving warning `App Start Span could not be finished. `Sentry.wrap` was called before `Sentry.init``..

![Uploading simulator_screenshot_1AE9231F-E880-4D45-9F12-4B31AC994793.png…](Warning Image)


Please resolve and push new version without any error and warning. cc @kahest

**Comment by kahest** [comment]
@Biplovkumar thanks for reporting - this is intentional. We recently added this warning to make you aware that `Sentry.wrap` is called before `Sentry.init` in your app, which can have side effects. You can resolve this by adapting your app's code. You can also opt to ignore this warning if you know that your app works correctly. The warning will of course only show up in local development.

**Comment by TomCorvus** [comment]
@Biplovkumar 
This is a fix on 5.9.0 version.
Init must be called before wrap.

Check this:
https://github.com/getsentry/sentry-react-native/releases/tag/5.9.0

**Comment by a-eid** [comment]
@TomCorvus we're still having this issue with version `5.19.1`
